// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbzpSGqbWHGYGFZ9F1zLb5_mJuLaq6Yww',
    appId: '1:66395852605:web:2e5449048ec42f59487f54',
    messagingSenderId: '66395852605',
    projectId: 'spotify-app001',
    authDomain: 'spotify-app001.firebaseapp.com',
    storageBucket: 'spotify-app001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9_DscVZMnyjqWkZO0oDk_OHozHR9SNF8',
    appId: '1:66395852605:android:1749748ff57ff89e487f54',
    messagingSenderId: '66395852605',
    projectId: 'spotify-app001',
    storageBucket: 'spotify-app001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSxTnL2EsL4FcFJMAIJR6T74rECuPYHVc',
    appId: '1:66395852605:ios:193d243e99c67a98487f54',
    messagingSenderId: '66395852605',
    projectId: 'spotify-app001',
    storageBucket: 'spotify-app001.firebasestorage.app',
    iosBundleId: 'com.example.spotifyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSxTnL2EsL4FcFJMAIJR6T74rECuPYHVc',
    appId: '1:66395852605:ios:193d243e99c67a98487f54',
    messagingSenderId: '66395852605',
    projectId: 'spotify-app001',
    storageBucket: 'spotify-app001.firebasestorage.app',
    iosBundleId: 'com.example.spotifyapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbzpSGqbWHGYGFZ9F1zLb5_mJuLaq6Yww',
    appId: '1:66395852605:web:0fa37e0153e06f17487f54',
    messagingSenderId: '66395852605',
    projectId: 'spotify-app001',
    authDomain: 'spotify-app001.firebaseapp.com',
    storageBucket: 'spotify-app001.firebasestorage.app',
  );
}
